name: Sigrid pull request feedback

on:
  - pull_request

jobs:
  sigridci:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Bash
        shell: bash
        run: "echo ${{ github.event.pull_request._links.self.href }}"
      - name: Bash
        shell: bash
        run: "echo ${{ github.event.pull_request.html_url }}"
      - name: Bash
        shell: bash
        run: "echo ${{ github.event.pull_request.url }}"
      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@markdown-feedback
        with:
          customer: opensource
          system: explorationday
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
      - name: Test pull request comment
        uses: mshick/add-pr-comment@v2
        if: always()
        with:
          message-id: sigrid
          message-path: sigrid-ci-output/feedback.md
          
