name: Publish to Sigrid

on:
  push:
    branches:
      - main
      - master

jobs:
  sigridci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@main
        with:
          customer: sigdelivery
          system: explorationday
          publishonly: true
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
